name: incidents-healthcheck

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v3 

    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0' 

    - name: Restore dependencies
      run: dotnet restore IncidentsHealthCheckSolution/IncidentsHealthCheckSolution.sln

    - name: Build
      run: dotnet build IncidentsHealthCheckSolution/IncidentsHealthCheckSolution.sln --configuration Release

    # - name: Run tests
    #   run: dotnet test IncidentsHealthCheckSolution/HealthCheckService.Tests/HealthCheckService.Tests.csproj --configuration Release --no-build
